@startuml

class Pizza {
  -crust
  -toppings
  -sauce
  +setCrust()
  +setToppings()
  +setSauce()
}

interface PizzaBuilder {
  #Pizza pizza_
  +makePizza()
  +buildCrust()
  +buildToppings()
  +buildSauce()
  +getPizza() : Pizza 
}

class ItalianPizzaBuilder {
}

class HawaiianPizzaBuilder {
}

class Cook {
  +preparePizza(Builder& builder)
  +openPizza()
}

PizzaBuilder *-left- Pizza
PizzaBuilder <|-- ItalianPizzaBuilder
PizzaBuilder <|-- HawaiianPizzaBuilder
Cook -left-> PizzaBuilder

@enduml
